pool: Default
jobs:
- job: start_app
  steps:
  - script: start-wecare
      
- job: start_zap_scan
  dependsOn: start_app
  steps:
  - script: export TARGET_IP=$(curl -XGET -s http://checkip.amazonaws.com/) && python3 -u Walkthrough.py

- job: Artifact_Results
  dependsOn: start_zap_scan
  steps:
  - task: CopyFiles@2
    inputs:
      sourceFolder: '$(Build.SourcesDirectory)'
      contents: '*.json'
      targetFolder: $(Build.ArtifactStagingDirectory)
  - task: PublishBuildArtifacts@1
    inputs:
      pathtoPublish: '$(Build.ArtifactStagingDirectory)'
      artifactName: zap_results
      
- job: stop_app
  dependsOn: Artifact_Results
  steps:
  - script: clean-docker || true

- job: stop_zap
  dependsOn: stop_app
  steps:
  - script: stop-zap || true
  
  
